language: ruby
rvm:
  - 2.2.0
addons:
  - postgresql: "9.3"
services:
  - redis-server
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database jib_job_travis;' -U postgres
