language: ruby
rvm:
  - 2.2.0
addons:
  postgresql: "9.4"
services:
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y wkhtmltopdf pdftk xvfb
  - sudo echo 'xvfb-run --server-args="-screen 0, 1024x768x24" /usr/bin/wkhtmltopdf $*' > /usr/local/bin/wkhtmltopdf.sh
  - sudo chmod a+x /usr/local/bin/wkhtmltopdf.sh
  - sudo ln -s /usr/local/bin/wkhtmltopdf.sh /usr/local/bin/wkhtmltopdf
before_script:
  - phantomjs --version
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database jib_job_travis;' -U postgres
cache: bundler