language: ruby
rvm:
  - 2.2.0
addons:
  postgresql: "9.4"
services:
  - redis-server
before_install:
  - sudo add-apt-repository -y ppa:moti-p/cc
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick
  - sudo apt-get install -y wkhtmltopdf pdftk
before_script:
  - phantomjs --version
  - cp config/database.yml.travis config/database.yml
  - cp config/mailer.yml.travis config/mailer.yml
  - psql -c 'create database jib_job_travis;' -U postgres
cache: bundler