language: ruby
rvm:
  - 2.2.0
addons:
  postgresql: "9.4"
services:
  - redis-server
before_script:
  - phantomjs --version
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database jib_job_travis;' -U postgres
  - npm install -g gulp
  - npm install
  - gulp dev:install