webapp:
  image: jibjob/app:latest
  command: server
  ports:
    - "8080:8080"
  volumes:
    - /vagrant_data:/app
    - /var/local/jibjob/bundle:/vendor/bundle
    - /var/local/jibjob/attachments:/app/public/system
  environment:
    - RAILS_ENV=development

worker:
  image: jibjob/app:latest
  command: worker -c 10 --queue default --queue mailers --queue logging
  volumes_from:
    - webapp
  environment:
    - RAILS_ENV=development
