# Note: Do not use in production
memcache:
  image: memcached
  ports:
    - "11211:11211"

redis:
  image: redis:3.0.0
  ports:
    - "6379:6379"
  volumes:
    - /var/local/jibjob/redis:/data

postgres:
  image: postgres:9.4.1
  ports:
    - "5432:5432"
  volumes:
    - /var/local/jibjob/postgres:/var/lib/postgresql/data
