rails:
  image: jibjob/app:latest
  volumes:
    - /vagrant_data:/app
    - /var/local/jibjob/bundle:/vendor/bundle
    - /var/local/jibjob/attachments:/app/public/system
  environment:
    - RAILS_ENV=development
    - DEFAULT_HOSTNAME=jibjob.dev
    - JIBJOB_POSTGRES_HOST=192.168.33.10
    - JIBJOB_POSTGRES_PORT=5432
    - JIBJOB_POSTGRES_DATABASE=jib_job_development
    - JIBJOB_POSTGRES_USER=postgres
    - MAILER_SMTP_HOST=
    - MAILER_SMTP_PORT=
    - MAILER_SMTP_DOMAIN=
    - MAILER_SMTP_USERNAME=
    - MAILER_SMTP_PASSWORD=
    - MAILER_DEFAULT_FROM=
    - SIDEKIQ_REDIS_URL=
    - SIDEKIQ_WEB_MOUNT=
    - JIBJOB_REDIS=
    - JIBJOB_REDIS_TEST=
    - CODECLIMATE_REPO_TOKEN=
    - PASSWORD_RESET_SECRET=
    - FACEBOOK_KEY=
    - FACEBOOK_SECRET=
    - TWITTER_KEY=
    - TWITTER_SECRET=
    - GOOGLE_CLIENT_KEY=
    - GOOGLE_CLIENT_SECRET=
    - DROPBOX_KEY=
    - DROPBOX_CLIENT=
    - STRIPE_SECRET_KEY=
    - STRIPE_PUBLIC_KEY=
    - MINI_PROFILER=
    - AWS_ACCESS_KEY_ID=
    - AWS_SECRET_KEY_ID=
    - S3_BUCKET_NAME=
    - WKHTMLTOPDF_BIN=/usr/local/bin/wkhtmltopdf
    - PDFTK_BIN=/usr/bin/pdftk
    - FONTS_INSTALL_DIR=/opt/fonts/truetype
