webapp:
  extends:
    file: common.yml
    service: rails
  command: server
  ports:
    - "80:80"

worker:
  extends:
    file: common.yml
    service: rails
  command: worker -c 10 --queue default --queue mailers --queue logging
